spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/delivera_dev
    username: delivera_user
    password: delivera_pass
    hikari:
      minimum-idle: 5
      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

app:
  jwt:
    secret: delivera-jwt-secret-key-para-desarrollo
    expiration: 86400
